language: node_js
node_js:
 - "lts/*"
sudo: false
dist: trusty
install:
 - npm ci
script:
  - npm run clean
  - npm run compile
  - npm run test  
after_success:
  - npm run coverage
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY